const { test, expect } = require('@playwright/test');
const AIPage = require('../core/ai-page');

/**
 * 🎯 AUTO-GENERATED TEST
 * Generated by: Test Agents - Generator Agent
 * Description: Navigate to saucedemo.com and verify page title is visible
 */

test.describe('Saucedemo - Page Title Verification', () => {
  
  test('should navigate to saucedemo and verify page title', async ({ page }) => {
    // Initialize AI-powered page object
    const aiPage = new AIPage(page);
    
    console.log('🚀 Starting test: Verify Saucedemo Page Title');
    
    // Step 1: Navigate to saucedemo.com
    console.log('📍 Step 1: Navigating to saucedemo.com');
    await aiPage.navigateTo('https://www.saucedemo.com');
    
    // Step 2: Wait for page to load
    console.log('⏳ Step 2: Waiting for page to load');
    await page.waitForLoadState('domcontentloaded');
    
    // Step 3: Verify page title is visible
    console.log('✓ Step 3: Verifying page title');
    await expect(page).toHaveTitle(/Swag Labs/);
    
    // Step 4: Verify login container is visible using standard selectors
    console.log('✓ Step 4: Verifying page elements');
    await expect(page.locator('.login_container')).toBeVisible();
    await expect(page.locator('#user-name')).toBeVisible();
    await expect(page.locator('#password')).toBeVisible();
    await expect(page.locator('#login-button')).toBeVisible();
    
    console.log('✅ Test completed successfully!');
  });

  test('should fill login form using AI-powered methods', async ({ page }) => {
    const aiPage = new AIPage(page);
    
    console.log('🚀 Starting AI-powered login test');
    
    // Navigate
    await aiPage.navigateTo('https://www.saucedemo.com');
    
    // Use AI-powered methods to interact with the form
    await aiPage.clickElement('username input field');
    await aiPage.fillField('username input', 'standard_user');
    await aiPage.fillField('password input', 'secret_sauce');
    await aiPage.clickElement('login button');
    
    // Verify successful login
    await page.waitForURL('**/inventory.html');
    console.log('✅ Login successful using AI-powered methods!');
  });
});
